spring.application.name=Poudlar2026
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=Azerty31!
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PoudlardM2;encrypt=false
